### ISSUE TITLE
pump botu

### ISSUE THREAD

**Issue by mustafa110** [lukacci/deltabot#10]
selam pump botu hakkında görüşmek istiyordum botunuzu çok beğendim yardımcı olurmusunuz

**Comment by lukacci** [comment]
Merhaba, sorunuzu burdan iletebilirsiniz.

**Comment by mustafa110** [comment]
Selam pump botu hakkında bilgi almak istiyorum ama yardımcı olurmusunuz yani nasıl hala hızlımı saniyenin 3/1 hızında coinlari alabiliyormuyuz acaba

Windows 10 için Posta ile gönderildi

Kimden: lukacci
Gönderilme: 22 Haziran 2019 Cumartesi 14:32
Kime: lukacci/deltabot
Bilgi: mustafa110; Author
Konu: Re: [lukacci/deltabot] pump botu (#10)

Merhaba, sorunuzu burdan iletebilirsiniz.

**Comment by lukacci** [comment]
Evet, maximum hızda alım yapılabilir. İnternet bağlantı hızının da yüksek olması önemli tabi bu noktada. 
Pump ve listing botu işlemlerinde saliseler dahi önemlidir. O yüzden süper hızlı olması adına her ayrıntıya dikkat edilerek geliştiriyoruz.

**Comment by mustafa110** [comment]
selam tekrardan pump botunu hala satıyormusunuz ve birde saniyenin 3/1
hızında alım yapıyor dimi varsa birde irtibat no su alabilirmiyim

**Comment by lukacci** [comment]
Evet, satışlar açık özellikler daha önce değindiğimiz gibi. Malesef irtibat numarası veremiyoruz.
