### ISSUE TITLE
I got an error upon installing 

### ISSUE THREAD

**Issue by jedwafu** [lukacci/deltabot#2]
![image](https://user-images.githubusercontent.com/6974564/45604410-b3286680-ba66-11e8-9e8c-01042d8f5972.png)

**Comment by lukacci** [comment]
Run this command 
`python3 -m pip install --upgrade pip
`

**Comment by jedwafu** [comment]
Thank you for that solution,. Now im getting this error:
![image](https://user-images.githubusercontent.com/6974564/45928885-eeea9100-bf7c-11e8-813b-4a6f471c12a7.png)

**Comment by lukacci** [comment]
I think the problem caused by python itself or it's modules. 
Maybe you forget to check to adding the python to system path when installing the python. 

Could you please look at google search results: 
https://www.google.com/search?q=dll+load+failed+python

**Comment by jedwafu** [comment]
yes i checked that one.
