### ISSUE TITLE
Full Version Feature

### ISSUE THREAD

**Issue by jedwafu** [lukacci/deltabot#3]
What do you mean by this? Should we pay for it?

**Comment by lukacci** [comment]
The difference between full and trial version is 1 second advantage and live support. You can pay for licence to upgrade pro version.

**Comment by jedwafu** [comment]
where can i reach you bro, how and how much can i purchase it?

**Comment by lukacci** [comment]
I added the necessary info to project homepage. Pro version is lifetime and only $100. No need to make extra purchases for additional bots on the future. You can pay  with the link on the homepage.
