### ISSUE TITLE
Error to execute

### ISSUE THREAD

**Issue by switecandy** [lukacci/deltabot#7]
![image](https://user-images.githubusercontent.com/42079143/46901269-e653ef00-ce86-11e8-8ab6-656a29647b9f.png)

I'm testing the robot, but it made a mistake. I have BTC balance, BNB balance, but error has occurred, does not perform the trade.

Help me please. If it's really good, I'm interested in buying the pro version to have more advantages.

**Comment by lukacci** [comment]
Could you please copy the config.json content to here (without api keys) ?

**Comment by switecandy** [comment]
![image](https://user-images.githubusercontent.com/42079143/46910615-f10d9300-cf1d-11e8-9742-008b961b0467.png)

I did our tests, gave this information, but in exchange nothing happened, the robot did not buy LTC as I gave the order. There was simply nothing in the exchange. That robot, the right one is to generate purchase order to get into the currency and he even create the sales order?

**Comment by switecandy** [comment]
![image](https://user-images.githubusercontent.com/42079143/46910678-af311c80-cf1e-11e8-9cb6-6d7975a0ec28.png)

I made new tests, in the cmd says that the orders were released, but nothing happened in the exchange. Did not buy and did not sell anything.

**Comment by lukacci** [comment]
You must  set the "trade_with_real_account" option to "True" in "binance_pumps" section.
