### ISSUE TITLE
Trying in Linux

### ISSUE THREAD

**Issue by Fibroblasto** [lukacci/deltabot#8]
Is it possible to run it in Linux?
If I try:
python3 ./binance_pump_bot.py

What I get is:

Traceback (most recent call last):
  File "./binance_pump_bot.py", line 4, in <module>
    import binance_pumps
ImportError: No module named 'binance_pumps'

**Comment by lukacci** [comment]
Sorry but deltabot only supports Windows at the moment because of some dependencies.
